In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
a.shape

(4,)

In [5]:
data = np.random.randint(10, 100, (4,4))

In [6]:
data.shape

(4, 4)

In [7]:
data

array([[63, 34, 68, 21],
       [86, 76, 84, 96],
       [65, 93, 71, 61],
       [12, 14, 43, 71]])

In [8]:
data.ndim

2

In [9]:
data.size

16

In [10]:
data.max()

96

In [11]:
np.sin(data)

array([[ 0.1673557 ,  0.52908269, -0.89792768,  0.83665564],
       [-0.92345845,  0.56610764,  0.73319032,  0.98358775],
       [ 0.82682868, -0.94828214,  0.95105465, -0.96611777],
       [-0.53657292,  0.99060736, -0.83177474,  0.95105465]])

In [12]:
np.linalg.inv(data)

array([[-0.00147124,  0.03387325, -0.02333195, -0.02531954],
       [-0.00941994, -0.00977892,  0.02271603, -0.0035082 ],
       [ 0.02475934, -0.0311459 ,  0.01282195,  0.02377354],
       [-0.01288898,  0.01506619, -0.0083012 ,  0.00465756]])

In [13]:
data.max(axis=1)

array([68, 96, 93, 71])

In [14]:
data.max(axis=0)

array([86, 93, 84, 96])

In [15]:
data.all

<function ndarray.all>

In [16]:
data.mean

<function ndarray.mean>

In [17]:
data.mean()

59.875

In [18]:
a + 5

array([6, 7, 8, 9])

In [19]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"])

array(['hi', 'hola', 'hi'], dtype='<U5')

In [20]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"])

array(['hi', 'hola', 'hi'], dtype='<U5')

In [21]:
a = np.array([1,2,3,4])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
list(a)

[1, 2, 3, 4]

In [24]:
type(a)

numpy.ndarray

In [25]:
np.random.random(5)

array([0.69425473, 0.77578221, 0.59735766, 0.57937718, 0.98893938])

In [26]:
np.random.random([5,1])

array([[0.22641849],
       [0.46807716],
       [0.20828446],
       [0.19858496],
       [0.92019275]])

In [27]:
np.random.randint(0, 100, 5)

array([11,  8, 39, 30, 59])

In [28]:
np.random.randint(0, 100, 5)

array([88, 89, 96,  0, 84])

In [29]:
y = np.array([[3, 5, 1], [1, 3, 9]])

In [30]:
y

array([[3, 5, 1],
       [1, 3, 9]])

In [31]:
y.transpose()

array([[3, 1],
       [5, 3],
       [1, 9]])

In [32]:
z = y + 3
z

array([[ 6,  8,  4],
       [ 4,  6, 12]])

In [33]:
z*y

array([[ 18,  40,   4],
       [  4,  18, 108]])

In [34]:
x = np.array([3, 5])

In [35]:
np.matmul(x,z)

array([38, 54, 72])

In [36]:
np.exp(x)

array([ 20.08553692, 148.4131591 ])

In [37]:
np.sin(x)

array([ 0.14112001, -0.95892427])

In [38]:
np.tanh(x)

array([0.99505475, 0.9999092 ])

In [39]:
x = np.array([4, 2, 9, -6, 5, 11, 3])

In [40]:
np.linalg.norm(x)

17.08800749063506

In [41]:
np.sqrt(4**2 + 2**2 + 9**2 + (-6)**2 + 5**2 + 11**2 + 3**2)

17.08800749063506

In [42]:
inputs = np.array([[3], [5]])
weights = np.array([[2], [4]])

In [43]:
inputs

array([[3],
       [5]])

In [44]:
inputs.shape

(2, 1)

In [45]:
np.transpose(weights)

array([[2, 4]])

In [46]:
weights.transpose()

array([[2, 4]])

In [47]:
weights.transpose().shape

(1, 2)

In [48]:
weights.transpose() * inputs

array([[ 6, 12],
       [10, 20]])

In [49]:
np.matmul(inputs, weights.transpose())

array([[ 6, 12],
       [10, 20]])

In [50]:
weights.transpose() @ inputs

array([[26]])

In [51]:
np.dot(weights.transpose(), inputs)

array([[26]])

In [52]:
np.tanh(np.dot(weights.transpose(), inputs))

array([[1.]])