In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [6]:
a.shape

(4,)

In [7]:
data = np.random.randint(10, 100, (4,4))

In [8]:
data.shape

(4, 4)

In [9]:
data

array([[98, 32, 60, 45],
       [44, 82, 98, 60],
       [16, 55, 51, 18],
       [18, 55, 17, 21]])

In [10]:
data.ndim

2

In [11]:
data.size

16

In [12]:
data.max()

98

In [13]:
np.sin(data)

array([[-0.57338187,  0.55142668, -0.30481062,  0.85090352],
       [ 0.01770193,  0.31322878, -0.57338187, -0.30481062],
       [-0.28790332, -0.99975517,  0.67022918, -0.75098725],
       [-0.75098725, -0.99975517, -0.96139749,  0.83665564]])

In [14]:
np.linalg.inv(data)

array([[ 1.47592913e-02, -1.56429601e-02,  1.16752200e-02,
         3.05978727e-03],
       [-1.41117173e-03, -1.01588175e-02,  1.46972322e-02,
         1.94515048e-02],
       [ 7.28520779e-05,  2.43649727e-03,  2.40978484e-02,
        -2.77728310e-02],
       [-9.01387068e-03,  3.80422758e-02, -6.80078644e-02,
         1.65347235e-02]])

In [15]:
data.max(axis=1)

array([98, 98, 55, 55])

In [16]:
data.max(axis=0)

array([98, 82, 98, 60])

In [17]:
data.all

<function ndarray.all>

In [18]:
data.mean

<function ndarray.mean>

In [19]:
data.mean()

48.125

In [20]:
a + 5

array([6, 7, 8, 9])

In [21]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"]

SyntaxError: unexpected EOF while parsing (<ipython-input-21-36471bca3e0c>, line 1)

In [22]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"])

array(['hi', 'hola', 'hi'], dtype='<U5')

In [23]:
from skimage.io import imread

In [24]:
a

array([1, 2, 3, 4])

In [25]:
a = np.array([1,2,3,4])

In [26]:
a

array([1, 2, 3, 4])

In [27]:
a.list

AttributeError: 'numpy.ndarray' object has no attribute 'list'

In [28]:
list(a)

[1, 2, 3, 4]

In [29]:
a.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [30]:
type(a)

numpy.ndarray

In [31]:
np.reshape(a)

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [32]:
np.reshape(a.shape)

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'