In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
a.shape

(4,)

In [6]:
data = np.random.randint(10, 100, (4,4))

In [7]:
data.shape

(4, 4)

In [8]:
data

array([[13, 93, 85, 96],
       [87, 44, 73, 20],
       [31, 63, 99, 71],
       [57, 48, 55, 34]])

In [9]:
data.ndim

2

In [10]:
data.size

16

In [12]:
data.max()

99

In [13]:
np.sin(data)

array([[ 0.42016704, -0.94828214, -0.17607562,  0.98358775],
       [-0.82181784,  0.01770193, -0.67677196,  0.91294525],
       [-0.40403765,  0.1673557 , -0.99920683,  0.95105465],
       [ 0.43616476, -0.76825466, -0.99975517,  0.52908269]])

In [14]:
np.linalg.inv(data)

array([[-0.04448075, -0.06840461,  0.02184384,  0.12021564],
       [ 0.09611785,  0.13526861, -0.07937001, -0.18521809],
       [ 0.02123505,  0.06212417,  0.00204792, -0.10077796],
       [-0.09547593, -0.17678412,  0.07211841,  0.25238131]])

In [15]:
data.max(axis=1)

array([96, 87, 99, 57])

In [16]:
data.max(axis=0)

array([87, 93, 99, 96])

In [17]:
data.all

<function ndarray.all>

In [18]:
data.mean

<function ndarray.mean>

In [19]:
data.mean()

60.5625

In [20]:
a + 5

array([6, 7, 8, 9])

In [21]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"]

SyntaxError: unexpected EOF while parsing (<ipython-input-21-36471bca3e0c>, line 1)

In [22]:
np.choose([1,2,1], choices=["hello", "hi", "hola", "hey"])

array(['hi', 'hola', 'hi'], dtype='<U5')

In [23]:
from skimage.io import imread

In [ ]:
img = imread('')