In [1]:
import numpy as np
# don't change any function name write you all code inside the function only for every question solution and return you output as mentioned in problem statement.

### 1. Write a NumPy program to create an array of all the even integers from a to b(both inclusive).

Input: 4,10

Output: [4,6,8,10]

In [8]:
def question_first_solution(a,b):
    if a%2!=0:
        a += 1
    if b%2==0:
        b += 1
    array=np.arange(a,b,2)
    return array
question_first_solution(4,10)

array([ 4,  6,  8, 10])

### 2. Write a NumPy program to create a vector with values from a to b and change the sign of the numbers in the range from c to d.

Input: 0, 20, 9, 15

Output: [  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13, -14, -15,  16,  17,  18,  19]

In [7]:
def question_second_solution(a,b,c,d):
    x = np.arange(a,b)
    x[(x >= c) & (x <= d)] *= -1
    return x
question_second_solution(0, 20, 9, 15)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19])

### 3. Write a NumPy program to create a mxn matrix, in which the elements on the borders will be equal to 1, and inside 0.

Input: 3, 4

Output:

         [[1., 1., 1., 1.],

          [1., 0., 0., 1.],
          
          [1., 1., 1., 1.]]

In [6]:
def question_third_solution(m,n):
    x = np.ones((m, n))
    x[1:-1, 1:-1] = 0
    return x
question_third_solution(3,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### 4. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

Input: [[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]]

Output: [[1., 2., 3.],
         [7., 8., 9.],
         [1., 0., 1.]]

In [5]:
def question_fourth_solution(x):
    x = np.array(x)
    return (x[~np.isnan(x).any(axis=1)])
    
x = [[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]]
question_fourth_solution(x)

array([[1., 2., 3.],
       [7., 8., 9.],
       [1., 0., 1.]])

### 5. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.
Input:

a = np.array([97, 101, 105, 110, 109])

b = np.array([0, 1, 2, 3, 4])

Note: Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110

Output: [1, 2, 4]

In [9]:
def question_fifth_solution(a,b):
    a = np.array(a)
    b = np.array(b)
    return (b[(100 < a) & (a < 110)])
a=[97, 101, 105, 110, 109]
b=[0, 1, 2, 3, 4]
print(question_fifth_solution(a,b))

[1 2 4]


### 6. Write a NumPy program to count the frequency of unique values in numpy array.

Input: [10,10,20,10,20,20,20,30, 30,50,40,40]

Output: [3, 4, 2, 2, 1]

In [10]:
def question_sixth_solution(a):
    a = np.array( a )
    unique_elements, counts_elements = np.unique(a, return_counts=True)
    return counts_elements
a =  [10,10,20,10,20,20,20,30, 30,50,40,40]
question_sixth_solution(a)


array([3, 4, 2, 2, 1])

### 7. Write a NumPy program to search the index of a given array in another given array.

Input: [[1,2,3], [4,5,6] , [7,8,9], [10, 11, 12]], [1,2,3]

Output: [1]

In [11]:
def question_seventh_solution(array, test_array):
    np_array = np.array(array)
    test_array = np.array(test_array)
    return (np.where((np_array == test_array).all(1))[0])

arr =[[1,2,3], [4,5,6] , [7,8,9], [10, 11, 12]]
test_array = [1,2,3]
print(question_seventh_solution(arr, test_array))

[0]


### 8. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

Input: [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]

Output: [1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j]

In [12]:
def question_eighth_solution(array):
    complex_num = np.array(array)
    
    return np.sort_complex(complex_num)
a = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
question_eighth_solution(a)

array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

### 9. Write a NumPy program to get the indices of the sorted elements of a given array.
Input: [1023, 5202, 6230, 1671, 1682, 5241, 4532]

Output: [0, 3, 4, 6, 1, 5, 2]

In [14]:
def question_ninth_solution(array):
    array = np.array(array)
    return np.argsort(array)

a = [1023, 5202, 6230, 1671, 1682, 5241, 4532]
question_ninth_solution(a)

array([0, 3, 4, 6, 1, 5, 2])

### 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Output: [[0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]                                                      
             [0 1 0 1 0 1 0 1]                                                      
             [1 0 1 0 1 0 1 0]]

In [15]:
def question_tenth_solution():
    x = np.zeros((8,8),dtype=int)
    x[1::2,::2] = 1
    x[::2,1::2] = 1
    return x
question_tenth_solution()



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])